export default 
{
  'Adrenal Gland': 'Adrenal Gland',
  Adipose0: 'Adipose-Subcutaneous', 
  Adipose1: 'Adipose-Visceral (Omentum)',
  Artery0: 'Artery-Aorta',
  Artery1: 'Artery-Coronary',
  Artery2: 'Artery – Tibial', 
  Brain0: 'Anterior cingulate cortex (BA24), Frontal Cortex (BA9) and Cortex',
  Brain1: 'Cerebellar Hemisphere and Cerebellum', 
  Brain2: 'Caudate (basal ganglia), Nucleus accumbens (basal ganglia) and Putamen (basal ganglia)',
  Brain3: 'Spinal cord (cervical c-1), and Substantia nigra',
  Brain4: 'Hypothalamus',
  Brain5: 'Amygdala and Hippocampus',
  'Breast-Mammary Tissue': 'Breast - Mammary Tissue', 
  'Colon-Sigmoid': 'Colon-Sigmoid', 
  Esophagus0: 'Esophagus - Gastroesophageal Junction',
  Esophagus1: 'Esophagus – Mucosa', 
  Esophagus2: 'Esophagus – Muscularis', 
  Heart0: 'Heart - Atrial Appendage', 
  Heart1: 'Heart - Left Ventricle', 
  Liver: 'Liver', 
  Lung: 'Lung',
  'Minor Salivary Gland': 'Minor Salivary Gland', 
  'Muscle - Skeletal': 'Muscle – Skeletal', 
  'Nerve - Tibial': 'Nerve – Tibial', 
  Ovary: 'Ovary', 
  Pituitary: 'Pituitary', 
  Prostate: 'Prostate', 
  Skin0: 'Skin - Not Sun Exposed (Suprapubic)', 
  Skin1: 'Skin-Sun Exposed (Lower leg)', 
  Testis: 'Testis', 
  Thyroid: 'Thyroid', 
  Uterus: 'Uterus',
  Vagina: 'Vagina',
  'Whole Blood': 'Whole Blood',
};
