export default 
{
  'Adrenal Gland': 'Adrenal Gland',
  'Adipose - Subcutaneous': 'Adipose0', 
  'Adipose - Visceral (Omentum)': 'Adipose1',
  'Artery - Aorta': 'Artery0',
  'Artery - Coronary': 'Artery1',
  'Artery - Tibial': 'Artery2', 
  Brain0: 'Brain0',
  Brain1: 'Brain1', 
  Brain2: 'Brain2',
  Brain3: 'Brain3',
  Brain4: 'Brain4',
  Brain5: 'Brain5',      
  'Breast - Mammary Tissue': 'Breast-Mammary Tissue', 
  'Colon - Sigmoid': 'Colon-Sigmoid', 
  'Esophagus - Gastroesophageal Junction': 'Esophagus0',
  'Esophagus - Mucosa': 'Esophagus1', 
  'Esophagus - Muscularis': 'Esophagus2', 
  'Heart - Atrial Appendage': 'Heart0', 
  'Heart - Left Ventricle': 'Heart1', 
  Liver: 'Liver', 
  Lung: 'Lung',
  'Minor Salivary Gland': 'Minor Salivary Gland', 
  'Muscle - Skeletal': 'Muscle - Skeletal', 
  'Nerve - Tibial': 'Nerve - Tibial', 
  Ovary: 'Ovary', 
  Pituitary: 'Pituitary', 
  Prostate: 'Prostate', 
  'Skin - Not Sun Exposed (Suprapubic)': 'Skin0', 
  'Skin - Sun Exposed (Lowerleg)': 'Skin1', 
  Testis: 'Testis', 
  Thyroid: 'Thyroid', 
  Uterus: 'Uterus',
  Vagina: 'Vagina',
  'Whole Blood': 'Whole Blood'
};
